In [2]:
import pandas as pd
from datetime import datetime
from functions import data_funcs
import ast
from pymongo import MongoClient
import creds


def load_all_steam_data():
    client = MongoClient(creds.CONNECTION_STRING)
    db = client["SteamCollectedData"]
    collection = db["Steam Data"]
    data = list(collection.find({}))
    df = pd.DataFrame(data)
    df.drop(columns=["_id"], inplace=True)

    list_columns = ["Genres", "Tags"]

    for col in list_columns:
        if col in df.columns:
            df[col] = df[col].apply(lambda x: 
                x if isinstance(x, list) 
                else ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") 
                else []
            )
    
    return df

In [3]:
df = load_all_steam_data()

In [4]:
len(df)

10375

In [5]:
df.tail()

,Rank,Game,Current,Peak,App ID,Player Hours,Genres,Release Date,Days Since Release,Date Collected,Tags,Recent Review Score,Recent Review Count,All Review Score,All Review Count
10370,9.0,Banana,80472,108835,2923300,42688015,"[Adventure, Casual, Simulation, Strategy, Free...","Apr 23, 2024",591.0,2025-12-05,"[Free to Play, Clicker, Singleplayer, 2D, Casu...",8.0,3193.0,6.0,20314.0
10371,25.0,Palworld,37177,135845,1623730,52256249,"[Action, Adventure, Indie, RPG, Early Access]","Jan 18, 2024",392.0,2025-02-13,[],NaN,NaN,NaN,NaN
10372,119.0,F1® 25,11699,15374,3059520,3186836,"[Racing, Simulation, Sports]","May 30, 2025",186.0,2025-12-02,"[Racing, Sports, Simulation, VR, Multiplayer, ...",8.0,3416.0,8.0,5168.0
10373,14.0,Where Winds Meet,60324,249851,3564740,74529454,"[Action, Adventure, RPG, Free To Play]","Nov 14, 2025",34.0,2025-12-18,"[Open World, Multiplayer, Free to Play, Souls-...",8.0,64436.0,8.0,48818.0
10374,159.0,Shadowverse: Worlds Beyond,7154,18958,2584990,4229647,"[Casual, RPG, Strategy, Free To Play]","Jun 14, 2025",182.0,2025-12-13,"[Free to Play, Card Battler, Trading Card Game...",5.0,488.0,4.0,6176.0

In [6]:
day = df[df["Date Collected"]=="2025-12-19"]
day

,Rank,Game,Current,Peak,App ID,Player Hours,Genres,Release Date,Days Since Release,Date Collected,Tags,Recent Review Score,Recent Review Count,All Review Score,All Review Count
38,170.0,YoloMouse,6461,11560,1283970,5810397,"[Animation & Modeling, Design & Illustration, ...","May 1, 2020",2058.0,2025-12-19,"[Utilities, Design & Illustration, Animation &...",8.0,45.0,8.0,1407.0
49,138.0,Age of Empires IV: Anniversary Edition,7932,20749,1466860,7307921,[Strategy],"Oct 28, 2021",1513.0,2025-12-19,"[Strategy, RTS, Base Building, Multiplayer, Wa...",8.0,1317.0,8.0,26602.0
177,28.0,Dead by Daylight,37557,62134,381210,27473596,[Action],"Jun 14, 2016",3475.0,2025-12-19,"[Horror, Multiplayer, Survival Horror, Online ...",8.0,8803.0,6.0,241743.0
299,101.0,Soundpad,12767,22527,629520,9438772,"[Audio Production, Utilities]","Sep 30, 2017",3002.0,2025-12-19,"[Utilities, Audio Production, Software, Music,...",9.0,1148.0,9.0,27186.0
419,151.0,Arma 3,7334,14712,107410,4911034,"[Action, Simulation, Strategy]","Sep 12, 2013",4481.0,2025-12-19,"[Military, Action, Multiplayer, Shooter, Simul...",8.0,1349.0,8.0,108916.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10275,173.0,Plants vs. Zombies™ Garden Warfare 2: Deluxe E...,6259,6676,1922560,1524114,"[Action, Casual, Strategy]","May 16, 2022",1313.0,2025-12-19,"[Zombies, PvP, Hero Shooter, Third-Person Shoo...",8.0,1729.0,8.0,17483.0
10299,123.0,Arma Reforger,9547,14853,1874880,5403632,"[Action, Simulation, Strategy]","Nov 16, 2023",764.0,2025-12-19,"[Military, Simulation, Shooter, Realistic, Act...",8.0,1599.0,6.0,24079.0
10321,118.0,Revolution Idle,9831,12885,2763740,7614756,"[Casual, Indie, Simulation, Free To Play]","May 1, 2025",232.0,2025-12-19,"[Idler, Casual, Simulation, Free to Play, Clic...",8.0,1621.0,8.0,5423.0
10336,71.0,Satisfactory,18221,31668,526870,11848506,"[Adventure, Indie, Simulation, Strategy]","Sep 10, 2024",465.0,2025-12-19,"[Base Building, Automation, Open World, Multip...",9.0,4385.0,9.0,125486.0
10337,129.0,The Elder Scrolls Online,9057,13909,306130,5921724,"[Action, Adventure, Massively Multiplayer, RPG]","May 22, 2017",3133.0,2025-12-19,"[RPG, MMORPG, Open World, Fantasy, Adventure, ...",6.0,534.0,8.0,72409.0